lfingsub = {
    'unhealthy':'healthy',
    'ground beef':'lean ground turkey',
    'bacon':'canadian bacon',
    'sausage':'lean ham',
    'chicken':'skinless chicken',
    'turkey':'skinless turkey',
    'duck':'skinless turkey',
    'goose':'skinless turkey',
    'beef chuck':'beef loin',
    'beef rib':'beef loin',
    'beef brisket':'beef loin',
    'pork spareribs':'pork tenderloin',
    'chorizo sausage':'turkey sausage',
    'milk':'skim milk',
    'cream':'evaporated skim milk',
    'iceberg lettuce':'arugula',
    'butter':'cooking spray',
    'margarine':'olive oil',
    'vegetable oil':'olive oil',
    'shortening':'fat-free margarine',
    'soy sauce':'low-sodium soy sauce',
    'alfredo':'marinara',
    'pasta':'whole wheat pasta',
    'sour cream':'Greek yogurt',
    'bread':'pita',
    'flour tortilla':'corn tortilla',
    'white bread':'whole wheat bread',
    'mayonnaise':'Greek yogurt',
    'eggs':'egg whites',
    'cream cheese':'fat-free ricotta cheese',
    'white rice':'brown rice'
}
