lfingsub = {
    'unhealthy':'healthy',
    'ground beef':'lean ground turkey',
    'bacon':'canadian bacon',
    'sausage':'lean ham',
    'chicken':'skinless chicken',
    'turkey':'skinless turkey',
    'duck':'skinless turkey',
    'goose':'skinless turkey',
    'beef chuck':'beef loin',
    'beef rib':'beef loin',
    'beef brisket':'beef loin',
    'pork spareribs':'pork tenderloin',
    'chorizo sausage':'turkey sausage',
    'milk':'skim milk',
    'cream':'evaporated skim milk',
    'iceberg lettuce':'arugula',
    'butter':'cooking spray',
    'margarine':'olive oil',
    'vegetable oil':'olive oil',
    'shortening':'fat-free margarine',
    'soy sauce':'low-sodium soy sauce',
    'alfredo':'marinara',
    'pasta':'whole wheat pasta',
    'sour cream':'Greek yogurt',
    'bread':'pita',
    'flour tortilla':'corn tortilla',
    'white bread':'whole wheat bread',
    'mayonnaise':'Greek yogurt',
    'eggs':'egg whites',
    'cream cheese':'fat-free ricotta cheese',
    'white rice':'brown rice'
}
hfingsub={
    'lean ground turkey':'ground beef',
    'canadian bacon':'bacon',
    'lean ham':'sausage',
    'skinless chicken':'chicken',
    'skinless turkey':'turkey',
    'turkey sausage':'chorizo sausage',
    'skim milk':'whole milk',
    'evaporated skim milk':'cream',
    'arugula':'iceberg lettuce',
    'cooking spray':'butter',
    'olive oil':'margarine',
    'olive oil':'vegetable oil',
    'fat-free margarine':'shortening',
    'low-sodium soy sauce':'soy sauce',
    'whole wheat pasta':'pasta',
    'corn tortilla':'flour tortilla',
    'whole wheat bread':'white bread',
    'egg whites':'eggs',
    'brown rice':'white rice'
}
lfcooksub = {
    'fry':'bake',
    'boil':'steam',
    'deep-fry':'bake',
    'pan fry':'bake'
}
