vegrank = {
  'tofu':1,
  'seitan':2,
  'tempeh':3,
  'eggplant':4,
  'zucchini':5,
  'mushroom':6,
  'asparagus':7,
  'black bean':8,
  'garbanzo bean':9,
  'kidney bean':10,
  'pinto bean':11,
  'chickpea':12,
  'lima bean':13,
  'canellini bean':14,
  'artichoke':15
}

vegsub = {
  'tofu':'chicken',
  'seitan':'beef',
  'tempeh':'pork',
  'eggplant':'chicken',
  'zucchini':'crab',
  'mushroom':'beef',
  'asparagus':'beef',
  'black bean':'ground beef',
  'garbanzo bean':'ground beef',
  'kidney bean':'ground beef',
  'pinto bean':'ground beef',
  'chickpea':'ground beef',
  'lima bean':'ground beef',
  'canellini bean':'ground beef',
  'artichoke':'beef'
}

meatsub = {  
  'beef tongue':'tofu',
  'beef tripe':'tofu',
  'beef stew meat':'tofu',
  'beef brisket':'tofu',
  'beef tenderloin':'tofu',
  'beef sirloin':'tofu',
  'beef short loin':'tofu',
  'beef chuck':'tofu',
  'ground beef':'black bean',
  'ground beef chuck':'black bean',
  'rump roast':'tempeh',
  'brisket':'tempeh',
  'chuck steak':'portobello mushroom',
  'filet mignon':'portobello mushroom',
  'flank steak':'portobello mushroom',
  'flank':'portobello mushroom',
  'oxtail':'seitan',
  'ribeye steak':'portobello mushroom',
  'ribeye':'portobello mushroom',
  'rib roast':'tempeh',
  'corned beef':'tofu',
  'corned beef brisket':'tofu',
  'pot roast':'tempeh',
  'veal':'tofu',
  'bison':'tofu',
  'buffalo':'tofu',
  'lamb':'tofu',
  'mutton':'tofu',
  'frog':'tofu',
  'goat':'tofu',
  'horse':'tofu',
  'frankfurter':'vegetarian sausage',
  'meatball':'vegetarian meatball',
  'meatloaf':'tofu',
  'sausage':'vegetarian sausage',
  'italian sausage':'vegetarian sausage',
  'chorizo':'soyrizo',
  'tendon':'tofu',
  'tripe':'tofu',
  'intestine':'tofu',
  'liver':'tofu',
  'kidney':'tofu',
  'tongue':'tofu',
  'hare':'tofu',
  'rabbit':'tofu',
  'abalone':'tofu',
  'whelk':'tofu',
  'snail':'tofu',
  'bacon':'vegetarian bacon',
  'bacon bits':'soybean',  
  'pork chop':'portobello mushroom',
  'pork tenderloin':'portobello mushroom',
  'pork rib':'seitan',
  'pork loin':'tofu',
  'pork loin roast':'tempeh',
  'pork sparerib':'seitan',
  'ground pork':'black bean',
  'pork roll':'vegetarian ham',
  'spam':'vegetarian ham',
  'ham':'vegetarian ham',
  'capon':'tofu',
  'chicken breast':'tofu',
  'chicken thighs':'tofu',
  'ground chicken':'chickpea',
  'cornish hen':'seitan',
  'prairie chicken':'seitan',
  'duck':'seitan',
  'foie gras':'avocado',
  'goose':'seitan',
  'grouse':'tofu',
  'guinea fowl':'tofu',
  'pheasant':'tofu',
  'quail':'tofu',
  'turkey':'tofurkey',
  'clam':'oyster mushroom',
  'crab':'imitation crab',
  'crawfish':'seitan',
  'cuttlefish':'shiitake mushroom',
  'eel':'tofu',
  'fish':'tofu',
  'tuna':'tofu',
  'anchovy':'tofu',
  'bass':'tofu',
  'black cod':'tofu',
  'bluefish':'tofu',
  'butter fish':'tofu',
  'blowfish':'tofu',
  'bream':'tofu',
  'brill':'tofu',
  'catfish':'tofu',
  'cod':'tofu',
  'dogfish':'tofu',
  'dorade':'tofu',
  'flounder':'tofu',
  'grouper':'tofu',
  'haddock':'tofu',
  'halibut':'tofu',
  'herring':'tofu',
  'ilish':'tofu',
  'john dory':'tofu',
  'kingfish':'tofu',
  'lamprey':'tofu',
  'lingcod':'tofu',
  'mackerel':'tofu',
  'mahi mahi':'tofu',
  'monkfish':'tofu',
  'mullet':'tofu',
  'chilean sea bass':'tofu',
  'pike':'tofu',
  'pollock':'tofu',
  'pomfret':'tofu',
  'pompano':'tofu',
  'sablefish':'tofu',
  'sanddab':'tofu',
  'sardine':'tofu',
  'salmon':'tofu',
  'sea bass':'tofu',
  'shad':'tofu',
  'skate':'tofu',
  'snakehead':'tofu',
  'snapper':'tofu',
  'sole':'tofu',
  'sturgeon':'tofu',
  'surimi':'tofu',
  'swordfish':'tofu',
  'tilapia':'tofu',
  'tilefish':'tofu',
  'trout':'tofu',
  'tuna':'tofu',
  'turbot':'tofu',
  'wahoo':'tofu',
  'whitefish':'tofu',
  'whiting':'tofu',
  'lobster':'imitation lobster',
  'mussel':'oyster mushroom',
  'octopus':'shiitake mushroom',
  'oyster':'oyster mushroom',
  'scallop':'seitan',
  'sea urchin':'shiitake mushroom',
  'shark':'seitan',
  'prawn':'seitan',
  'shrimp':'seitan',
  'calamari':'shiitake mushroom',
  'squid':'shiitake mushroom',
  'reindeer':'tempeh',
  'venison':'tempeh',
  'elk':'tempeh',
  'moose':'tempeh'
  #'beef':'tofu',
  #'pork':'tofu',
  #'chicken':'tofu'
}